import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import Progress from "./Progress";
import I18nProvider from "./I18nProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body className={`w-full h-screen antialiased`}>
        <Progress>
          <I18nProvider>{children}</I18nProvider>
          <Toaster position="top-center" />
        </Progress>
      </body>
    </html>
  );
}
